#
# Created by MikBac on 17.12.2025
#
services:
  postgres-master:
    image: postgres:17.2
    container_name: pg-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./master-init/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./master-init/01-create-users.sql:/docker-entrypoint-initdb.d/01-create-users.sql
      - ./master-init/02-create-sample-data.sql:/docker-entrypoint-initdb.d/02-create-sample-data.sql
    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - listen_addresses=*
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - pg-cluster-sr-network

  postgres-replica1:
    image: postgres:17.2
    container_name: pg-replica1
    depends_on:
      - postgres-master
    environment:
      - PGPASSWORD=replicator1
    ports:
      - "5433:5432"
    volumes:
      - pg-replica1-data:/var/lib/postgresql/data
    entrypoint: >
      bash -c "
        until pg_isready -h postgres-master -p 5432; do sleep 1; done;
        rm -rf /var/lib/postgresql/data/*
        pg_basebackup -h postgres-master -U replicator --checkpoint=fast -D /var/lib/postgresql/data --slot=replica_name_1 -C --port=5432 -Fp -Xs -P -R
        exec docker-entrypoint.sh postgres
      "
    networks:
      - pg-cluster-sr-network

  postgres-replica2:
    image: postgres:17.2
    container_name: pg-replica2
    depends_on:
      - postgres-master
    environment:
      - PGPASSWORD=replicator1
    ports:
      - "5434:5432"
    volumes:
      - pg-replica2-data:/var/lib/postgresql/data
    entrypoint: >
      bash -c "
        until pg_isready -h postgres-master -p 5432; do sleep 1; done;
        rm -rf /var/lib/postgresql/data/*
        pg_basebackup -h postgres-master -U replicator --checkpoint=fast -D /var/lib/postgresql/data --slot=replica_name_2 -C --port=5432 -Fp -Xs -P -R
        exec docker-entrypoint.sh postgres
      "
    networks:
      - pg-cluster-sr-network

volumes:
  pg-master-data:
  pg-replica1-data:
  pg-replica2-data:

networks:
  pg-cluster-sr-network:
